In [29]:
import pandas as pd

#### di sini langkah awal kita adalah dengan membuat penampungan dari semua file dataset kita

In [30]:
file_saham={
    'bbca':'/content/BBCA.JK_10_years.csv',
    'bbni':'/content/BBNI.JK_10_years.csv',
    'bbri':'/content/BBRI.JK_10_years.csv',
    'bmri':'/content/BMRI.JK_10_years.csv'
}

#### langkah selanjutnya adalah dengan kita melakukan looping untuk menjadikan penampungan di atas menjadi satu dataframe

In [31]:
# 2. Kita siapkan keranjang kosong (List) untuk menampung data sementara
list_dataframe = []

# 3. Kita lakukan perulangan (looping) untuk membaca dan memproses file satu per satu
for kode_saham, nama_file in file_saham.items():

    # Membaca file CSV
    df_sementara = pd.read_csv(nama_file)

    # PENTING: Kita tambahkan kolom baru agar saat digabung, kita tahu ini data bank apa
    df_sementara['Kode_Saham'] = kode_saham

    # Masukkan data yang sudah dilabeli ini ke dalam keranjang
    list_dataframe.append(df_sementara)

##### Sekarang tinggal kita gabungkan

In [32]:
df = pd.concat(list_dataframe, ignore_index=True)
df.head(),df.tail()

(                        Date    Adj Close   Close    High     Low    Open  \
 0  2014-12-08 00:00:00+00:00  2246.477539  2655.0  2680.0  2645.0  2655.0
 1  2014-12-09 00:00:00+00:00  2242.247314  2650.0  2680.0  2630.0  2660.0
 2  2014-12-10 00:00:00+00:00  2250.708008  2660.0  2675.0  2630.0  2630.0
 3  2014-12-11 00:00:00+00:00  2246.477539  2655.0  2675.0  2645.0  2660.0
 4  2014-12-12 00:00:00+00:00  2242.247314  2650.0  2665.0  2640.0  2640.0

      Volume Kode_Saham
 0  37435500       bbca
 1  38254000       bbca
 2  32998000       bbca
 3  54459500       bbca
 4  50302000       bbca  ,
                            Date  Adj Close   Close    High     Low    Open  \
 9887  2024-11-26 00:00:00+00:00     6400.0  6400.0  6600.0  6325.0  6600.0
 9888  2024-11-28 00:00:00+00:00     6450.0  6450.0  6525.0  6350.0  6350.0
 9889  2024-11-29 00:00:00+00:00     6150.0  6150.0  6375.0  6125.0  6325.0
 9890  2024-12-02 00:00:00+00:00     6000.0  6000.0  6250.0  5975.0  6175.0
 9891  2024-12-03 00:00:00+00:00     6275.0  6275.0  6275.0  6100.0  6100.0

          Volume Kode_Saham
 9887  107194300       bmri
 9888   81883200       bmri
 9889  157628700       bmri
 9890  114555300       bmri
 9891   99509800       bmri  )

#### Sekarang kita akan masuk ke dalam pembersihan data termasuk outlier

In [33]:
df.describe()

,Adj Close,Close,High,Low,Open,Volume
count,9892.000000,9892.000000,9892.000000,9892.000000,9892.000000,9.892000e+03
mean,3696.681565,4206.490831,4251.594670,4162.227313,4208.214713,9.655135e+07
std,1919.855613,1819.085576,1831.454590,1806.257330,1818.980241,7.632074e+07
min,1074.429321,1509.064819,1522.700928,1449.974976,1463.611084,0.000000e+00
25%,2297.476563,2843.750000,2875.000000,2809.760620,2850.000000,5.047790e+07
50%,3100.736816,3750.000000,3800.000000,3715.000000,3761.250000,7.847575e+07
75%,4631.291992,4950.000000,5000.000000,4900.000000,4950.000000,1.191093e+08
max,10895.657230,10950.000000,10950.000000,10775.000000,10900.000000,1.062862e+09

##### hasil pengamatan
1.terlihat bahwa untuk jumlah baris cukup konsisten menandakan data lengkap <br>
2.nah outlier pertama yang kita temukan adalah ada angka 0 dimana harus kita hilangkan

In [34]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [38]:
df_apus=df[df['volume']>0]#kita hilangkan yang <=0

In [37]:
df_apus.describe()

,adj_close,close,high,low,open,volume
count,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000,9.621000e+03
mean,3716.985029,4222.319444,4268.693748,4176.809131,4224.091884,9.927096e+07
std,1937.127352,1836.057975,1848.244386,1823.369438,1835.935367,7.562366e+07
min,1074.429321,1509.064819,1522.700928,1449.974976,1463.611084,5.985400e+06
25%,2300.585693,2840.860107,2875.000000,2806.250000,2845.405518,5.272420e+07
50%,3110.242432,3762.500000,3809.025146,3725.000000,3763.571289,8.011163e+07
75%,4684.129883,4980.000000,5050.000000,4937.500000,4990.000000,1.210053e+08
max,10895.657230,10950.000000,10950.000000,10775.000000,10900.000000,1.062862e+09

In [42]:
# 1. Pastikan kolom 'date' dalam format datetime
df_apus['date'] = pd.to_datetime(df_apus['date'])
df_apus['date'] = df_apus['date'].dt.date

/tmp/ipykernel_2391/1188784203.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_apus['date'] = pd.to_datetime(df_apus['date'])
/tmp/ipykernel_2391/1188784203.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_apus['date'] = df_apus['date'].dt.date

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9892 entries, 0 to 9891
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        9892 non-null   object
 1   adj_close   9892 non-null   float64
 2   close       9892 non-null   float64
 3   high        9892 non-null   float64
 4   low         9892 non-null   float64
 5   open        9892 non-null   float64
 6   volume      9892 non-null   int64
 7   kode_saham  9892 non-null   object
dtypes: float64(5), int64(1), object(2)
memory usage: 618.4+ KB

In [44]:
df_apus.head()

,date,adj_close,close,high,low,open,volume,kode_saham
0,2014-12-08,2246.477539,2655.0,2680.0,2645.0,2655.0,37435500,bbca
1,2014-12-09,2242.247314,2650.0,2680.0,2630.0,2660.0,38254000,bbca
2,2014-12-10,2250.708008,2660.0,2675.0,2630.0,2630.0,32998000,bbca
3,2014-12-11,2246.477539,2655.0,2675.0,2645.0,2660.0,54459500,bbca
4,2014-12-12,2242.247314,2650.0,2665.0,2640.0,2640.0,50302000,bbca

##### sekarang cek missing value dan duplicate pada dataframe

In [47]:
print(df_apus.isnull().sum())

date          0
adj_close     0
close         0
high          0
low           0
open          0
volume        0
kode_saham    0
dtype: int64

In [48]:
print(df_apus.duplicated().sum())

0

#### Sekarang proses pemrosesan data telah selesai